name: u-sleep
channels:
  - defaults
  - tensorflow
dependencies:
  - pip=20.1.1
  - python=3.7.7
  - readline=8.0
  - setuptools=47.3.1
  - tk=8.6.10
  - wheel=0.34.2
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - cachetools==4.0.0
    - carbontracker==1.1.2
    - certifi==2019.11.28
    - chardet==3.0.4
    - cloudpickle==1.1.1
    - cycler==0.10.0
    - decorator==4.4.1
    - gast==0.2.2
    - geocoder==1.38.1
    - grpcio==1.26.0
    - h5py==2.10.0
    - idna==2.8
    - joblib==0.14.1
    - Keras-Applications==1.0.8
    - Keras-Preprocessing==1.1.0
    - kiwisolver==1.1.0
    - Markdown==3.1.1
    - matplotlib==3.1.3
    - memory-profiler==0.57.0
    - mne==0.21.0
    - mpunet==0.2.6
    - nibabel==3.0.0
    - numexpr==2.7.1
    - numpy==1.18.1
    - opt-einsum==3.1.0
    - pandas==1.0.1
    - protobuf==3.11.2
    - psutil==5.6.7
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pynvml==8.0.4
    - pyparsing==2.4.6
    - python-dateutil==2.8.1
    - pytz==2019.3
    - rsa==4.0
    - ruamel.base==1.0.0
    - ruamel.yaml==0.16.5
    - ruamel.yaml.clib==0.2.0
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - six==1.13.0
    - tables==3.6.1
    - tabulate==0.8.6
    - tensorboard==2.1.0
    - tensorflow>=2.1.0
    - tensorflow-addons==0.7.0
    - tensorflow-probability==0.8.0
    - termcolor==1.1.0
    - urllib3==1.25.7
    - Werkzeug==0.16.0
    - wfdb>=3.1.1
    - wrapt==1.11.2
